services:
  time-ledger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time-ledger
    ports:
      - "3030:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_SITE_URL: https://timeledger.blazorserver.com
    networks:
      - shared_bridge
    restart: unless-stopped

networks:
  shared_bridge:
    external: true
